name: Lighthouse CI
on:
  pull_request:
permissions:
  contents: read
  pull-requests: write

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # pnpm 활성화
      - name: Enable pnpm (Corepack)
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate
          pnpm -v

      # 캐시 (선택이지만 추천)
      - name: Get pnpm store path
        id: pnpm-store
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      # 의존성 설치 & 빌드
      - run: pnpm install --frozen-lockfile
      - run: pnpm build # Vite -> dist/

      # Lighthouse CI 실행
      - name: Run Lighthouse CI
        id: lhci
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: ./.lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3

      # PR에 링크 코멘트
      - name: Comment report links
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          message: |
            Lighthouse CI reports:
            ${{ steps.lhci.outputs.links }}
