name: Lighthouse CI
on:
  pull_request:
permissions:
  contents: read
  pull-requests: write

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci
      - run: npm run build # Vite 빌드 -> dist/ 생성

      - name: Run Lighthouse CI
        id: lhci
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: ./.lighthouserc.json
          uploadArtifacts: true # HTML/JSON 리포트 아티팩트 보관
          temporaryPublicStorage: true # 7일 링크 생성(코멘트에 첨부)
          runs: 3

      - name: Comment report links on PR
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          message: |
            Lighthouse CI reports:
            ${{ steps.lhci.outputs.links }}
